<?php

/*
 * Copyright(c) neurotech CO.,LTD. All Rights Reserved.
 */

namespace Customize\Repository;

use Customize\Entity\CustomerChatConversation;
use Customize\Entity\CustomerChatInfo;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Eccube\Repository\AbstractRepository;

/**
 * CustomerChatConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerChatConversationRepository extends AbstractRepository
{
    /**
     * CustomerChatConversationRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CustomerChatConversation::class);
    }

    public function newConversation()
    {
        $Conversation = new CustomerChatConversation();
        return $Conversation;
    }
}
